import { motion } from 'framer-motion'
import { ArrowUpRight } from 'lucide-react'
import { SectionHeading } from './SectionHeading'

const cases = [
  { tag:'Строительная площадка', title:'Подготовка территории под строительство', task:'Земляные работы и перемещение грунта на объекте.', result:'Экскаватор-погрузчик с оператором и вывоз грунта самосвалами.', image:'/images/fregat-fleet-03.jpg' },
  { tag:'Поставка материалов', title:'Доставка щебня напрямую на объект', task:'Организовать регулярную поставку с карьера без простоев бригады.', result:'Самосвалы по согласованному графику и контроль каждой подачи.', image:'/images/fregat-fleet-02.jpg' },
  { tag:'Промышленный объект', title:'Вывоз грунта с территории объекта', task:'Организовать вывоз грунта без остановки основных работ.', result:'Самосвалы тяжёлого класса по согласованному графику.', image:'/images/fregat-fleet-01.jpg' }
]

export function CasesSection(){return <section id="cases" className="relative z-10 py-24 lg:py-36"><div className="container-pad"><SectionHeading index="05" label="практика" title="Задачи, которые решаем на объектах" copy="Обезличенные примеры типовых работ компании — без вымышленных названий клиентов и рекламных обещаний."/><div className="grid gap-4 lg:grid-cols-3">{cases.map((item,index)=><motion.article initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.1}} key={item.title} className="group card overflow-hidden"><div className="relative h-56 overflow-hidden"><img src={item.image} alt={item.title} className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-panel to-transparent"/><span className="absolute bottom-4 left-5 text-[9px] font-bold uppercase tracking-[.18em] text-orange">{item.tag}</span></div><div className="p-6"><h3 className="min-h-16 font-display text-lg uppercase leading-snug">{item.title}</h3><div className="mt-6 space-y-4 border-t border-line pt-5 text-sm leading-6"><p><span className="mb-1 block text-[9px] uppercase tracking-wider text-white/25">Задача</span><span className="text-white/55">{item.task}</span></p><p><span className="mb-1 block text-[9px] uppercase tracking-wider text-white/25">Решение</span><span className="text-white/70">{item.result}</span></p></div><a href="#contact" className="mt-6 flex items-center gap-2 text-[10px] font-bold uppercase tracking-wider text-orange">Обсудить похожую задачу <ArrowUpRight className="size-4"/></a></div></motion.article>)}</div></div></section>}
