import { ArrowUpRight, Check } from 'lucide-react'
import { motion } from 'framer-motion'
import { SectionHeading } from './SectionHeading'

const formats = [
  {tag:'Аренда',title:'Почасовая или посменная',text:'Для спецтехники и грузового транспорта.',list:['Техника с оператором','Минимальный заказ уточняет диспетчер','Подача считается по адресу объекта']},
  {tag:'Логистика',title:'Стоимость за рейс',text:'Для материалов, мусора и перевозки грузов.',list:['Учитываем объём и маршрут','Подбираем подходящий кузов','Фиксируем условия до выезда']},
  {tag:'Комплекс',title:'Расчёт под задачу',text:'Когда нужно несколько машин или этапов работ.',list:['Единый ответственный','Согласованный график','Документы для юридических лиц']}
]

export function PricingSection(){return <section id="prices" className="relative z-10 border-y border-line bg-panel py-24 lg:py-36"><div className="container-pad"><SectionHeading index="04" label="стоимость" title="Считаем цену под условия объекта" copy="Стоимость зависит от типа техники, срока аренды, маршрута и объёма. Оставьте параметры задачи — подготовим понятный расчёт без скрытых работ."/><div className="grid lg:grid-cols-3">{formats.map((item,index)=><motion.article initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.1}} key={item.title} className={`group border border-line p-7 ${index===1?'relative bg-orange text-white lg:-translate-y-4 lg:shadow-glow':'bg-ink'}`}><div className="mb-10 flex items-center justify-between text-[9px] font-bold uppercase tracking-[.2em]"><span className={index===1?'text-white/70':'text-orange'}>{item.tag}</span><span className="text-white/25">0{index+1}</span></div><h3 className="min-h-14 font-display text-xl uppercase">{item.title}</h3><p className="mt-4 min-h-12 text-sm leading-6 text-white/50">{item.text}</p><ul className="mt-7 space-y-3 border-t border-white/15 pt-6">{item.list.map(text=><li key={text} className="flex gap-3 text-xs text-white/60"><Check className="size-4 shrink-0"/>{text}</li>)}</ul><a href="#contact" className="mt-8 flex items-center justify-between border-t border-white/15 pt-5 text-[10px] font-bold uppercase tracking-wider">Получить расчёт <ArrowUpRight className="size-4 transition group-hover:rotate-45"/></a></motion.article>)}</div></div></section>}
