import { Header } from './components/Header'
import { Hero } from './components/Hero'
import { ServicesSection } from './components/ServicesSection'
import { FleetSection } from './components/FleetSection'
import { ProcessSection } from './components/ProcessSection'
import { PricingSection } from './components/PricingSection'
import { StatsSection } from './components/StatsSection'
import { ReviewsSection } from './components/ReviewsSection'
import { ContactSection } from './components/ContactSection'
import { CasesSection } from './components/CasesSection'
import { ScrollProgress } from './components/ScrollProgress'
import { AnimatedBackground } from './components/AnimatedBackground'
import { MobileActionBar } from './components/MobileActionBar'
export default function App(){return <main className="overflow-clip bg-ink pb-20 text-cream md:pb-0"><ScrollProgress/><AnimatedBackground/><Header/><Hero/><ServicesSection/><FleetSection/><ProcessSection/><PricingSection/><StatsSection/><CasesSection/><ReviewsSection/><ContactSection/><MobileActionBar/></main>}
